# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure prometheus-postgres-exporter path exist
  ansible.builtin.file:
    path: "{{ prometheus_postgres_exporter_base_path }}"
    state: directory
    mode: 0700
    owner: "{{ prometheus_postgres_exporter_uid }}"
    group: "{{ prometheus_postgres_exporter_gid }}"

- name: Ensure prometheus-postgres-exporter support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ prometheus_postgres_exporter_base_path }}/{{ item }}"
    owner: "{{ prometheus_postgres_exporter_uid }}"
    group: "{{ prometheus_postgres_exporter_gid }}"
    mode: 0640
  with_items:
    - env
    - labels

- name: Ensure prometheus-postgres-exporter image is pulled
  community.docker.docker_image:
    name: "{{ prometheus_postgres_exporter_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ prometheus_postgres_exporter_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else prometheus_postgres_exporter_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure prometheus-postgres-exporter container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ prometheus_postgres_exporter_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure prometheus-postgres-exporter systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/prometheus-postgres-exporter.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ prometheus_postgres_exporter_identifier }}.service"
    mode: 0644
